### ISSUE TITLE
KK_UncensorSelector Female Vagina Setting Missing

### ISSUE THREAD

**Issue by Terell2018** [DeathWeasel1337/KK_Plugins#11]
there no female vagina in plugins setting.

**Comment by DeathWeasel1337** [comment]
The vagina is built in to the body for females, unlike with males where the penis is a separate object. To set a specific vagina for a female you must set the body. Download all the uncensors from https://mega.nz/#F!upYGBTAZ!S1lMalC33LYEditk7GwzgQ!n54h1KZS and place them in your mods folder then select a female body for your characters.
