### ISSUE TITLE
Koikatsu KK_HCtrl0.0.0

### ISSUE THREAD

**Issue by Terell2018** [DeathWeasel1337/KK_Plugins#12]
i found the plugins call KK_HCtrl0.0.0 from here https://ux.getuploader.com/56e4_xXVv/index/date/desc/1 and it automatic speed & motion forced switching plug-in 0.0.0 when H ... but the plugin it in Japanese.

**Comment by DeathWeasel1337** [comment]
It looks like a useful plugin, thanks for bringing it to my attention. I may do a translation of it sometime in the future.

The Issues feature of Github is more aimed at reporting bugs or other problems with the project, if you'd like to talk you can just join the Koikatsu Discord channel, you'll find me there with the name Anon11. https://discord.gg/urDt8CK
