### ISSUE TITLE
KK LO Male Uncensor in Uncensor Selector

### ISSUE THREAD

**Issue by Matihood1** [DeathWeasel1337/KK_Plugins#16]
Hey,

Are you planning on adding the KK LO male uncensor to your selector? Currently, there's only the female one available in your mod and while it's not a problem for Koikatsu as I can just use the standalone uncensor instead of the Uncensor Selector, in case of EC things get a little problematic...

**Comment by DeathWeasel1337** [comment]
Hi there,

I have no intention of adding the KK LO male uncensor, I've never liked it and the fact that it doesn't do color matching means that it's on compatible with a very small number of characters. If you want to convert it for use with UncensorSelector, you only need to modify the manifest.xml of the mod with some extra data and UncensorSelector will load it. See https://github.com/DeathWeasel1337/KK_Plugins/blob/master/Core_UncensorSelector/Template.xml or unzip and inspect other uncensors to see how they're set up.
