### ISSUE TITLE
Koikatsu party

### ISSUE THREAD

**Issue by Terell2018** [DeathWeasel1337/KK_Plugins#17]
There a koikatsu party on stream that it already translator. and some mod work excerpt uncensor selector

**Comment by DeathWeasel1337** [comment]
UncensorSelector and others rely on KKAPI by Marco, he's in the process of updating it for Koikatsu Party. Keep an eye out for it in the coming days. Once KKAPI is updated UncensorSelector should work perfectly.

**Comment by DeathWeasel1337** [comment]
KKAPI has been updated for Koikatsu Party so UncensorSelector should work once more
https://github.com/ManlyMarco/KKAPI/releases
