### ISSUE TITLE
Request for KK_GUIDMigration

### ISSUE THREAD

**Issue by nirvana358888** [DeathWeasel1337/KK_Plugins#2]
Current accessories seem to be migrates from 1 to 20th item, but if you can correspond to MoreAccessories please.

Thanks for the wonderful plugins

**Comment by DeathWeasel1337** [comment]
That's definitely something I'd like to see happen, but MoreAccessories makes it very difficult. At the moment I know of no way to do so without introducing a dependency on MoreAccessories which is something I want to avoid. Likely MoreAccessories is the plugin that needs to get fixed for this to happen.

**Comment by nirvana358888** [comment]
Thank you for your reply. I understand.

**Comment by Joan6694** [comment]
I'll be able to take a look at this issue in approximately two weeks.

**Comment by DeathWeasel1337** [comment]
Resolved as of KK_GUIDMigration version 1.5 and MoreAccessores version v1.0.4
