### ISSUE TITLE
Could not load [Uncensor Selector] because it has missing dependencies: KSOX

### ISSUE THREAD

**Issue by QGCmaster** [DeathWeasel1337/KK_Plugins#23]
Could not load [Uncensor Selector] because it has missing dependencies: KSOX
Bepinex √
KKAPI √
But what is KSOX anyway :(

**Comment by cyb3rm4n** [comment]
it's https://github.com/ManlyMarco/Koikatu-Overlay-Mods but the release version 5.0.2 is cant be loaded by latest bepinex. I tried to rebuild it from github but got TypeLoaderException without stacktrace.

**Comment by DeathWeasel1337** [comment]
Right, KSOX is Marco's overlay mods. I added a note to the readme about it. Make sure to update BepisPlugins, Overlay Mods, and AI API. Plugins often rely heavily on each other and new games such as AI Girl require frequent updates.

Also make sure you're using the latest build of BepInEx https://builds.bepis.io/projects/bepinex_be These plugins require the latest build, the latest release (RC1) is not sufficient.
