### ISSUE TITLE
Issue with Pushup Mod

### ISSUE THREAD

**Issue by zeranno** [DeathWeasel1337/KK_Plugins#28]
I've noticed a bit of a silly quirk on the Pushup Mod. It seems to be saving the Pushup data to no particular part of the card... basically, It's not associated with the outfit. load any part of a character, you get the pushup data of that character. It's a bit... unintuitive and resulted in a good deal of reworking when making my last character. It feels a bit strange that it's not on the outfit data, as that might even allow the data to be saved to coordinate cards. I know you just ported it but thought I'd let you know.

**Comment by DeathWeasel1337** [comment]
Fixed as of v1.1
