### ISSUE TITLE
Uncensor selector dropdown list exceeding the window, some mods can't be selected.

### ISSUE THREAD

**Issue by WITS-fe** [DeathWeasel1337/KK_Plugins#29]
Bug as shown below.
The game windowed size is 1728x972. I've just upgraded to the latest Sideloader Modpack - KK_UncensorSelector.
May a scroll bar be added, like the shader dropdown list?

![20200119175922](https://user-images.githubusercontent.com/58023436/72679178-b82c7880-3ae7-11ea-8995-218cad93470d.png)

**Comment by WITS-fe** [comment]
I found that after being added the plugin KK_InvisibleBody,, it shows entire list normally.

![202001301829](https://user-images.githubusercontent.com/58023436/73442403-be481200-438f-11ea-9c25-f95fe8be3b85.png)

**Comment by ManlyMarco** [comment]
Fixed in https://github.com/IllusionMods/IllusionModdingAPI/commit/2c04b27df34d9787d7eea97a3e20768eb023f991
