### ISSUE TITLE
Problem with Random Character Generator values not persisting

### ISSUE THREAD

**Issue by Plus9000** [DeathWeasel1337/KK_Plugins#30]
After generating a character, moving to different tab will cause chest to snap back to default setting.

(also would be great to have a config to blacklist certain character settings  ;) but w/e

**Comment by DeathWeasel1337** [comment]
Seems to work fine for me. It might be a compatibility issue with KK_Pushup, could you try testing it with that plugin removed and also update it to the latest version if you don't already have it?

**Comment by Plus9000** [comment]
I don't appear to have the KK_pushup mod. The RCG is at 1.0, which should
be the most up-to-date.

It's funny, 'cause I know I had the pushup mod at one point, but KK_manager
doesn't find it, and doing a search of my mods doesn't turn it up either.

I just hit download all on the KK_Manager, is there another mod that might
conflict? Though I doubt anybody knows all the mod conflicts there.
