### ISSUE TITLE
KK_ForceHighPoly 1.2 and SliderUnlocker

### ISSUE THREAD

**Issue by Timo713** [DeathWeasel1337/KK_Plugins#34]
I think this was posted before, but there was no answer. The problem here is that when loading a character that has slider values above 100 or below 0, SOME of these values will reset to their vanilla limits in the school exploring mode, even with KK_ForceHighPoly on. This is most noticeable in characters with big breasts where they will be shown smaller, but also happens with hips and heads. 

I doesn't happen to all sliders. For example, heights load just fine. And looks like KKABMX values are not affected either, but I haven't tested them all.

I've noticed the problem is still present without KK_ForceHighPoly, so it could be a problem with SliderUnlocker too. But then, something that surprised me is that the KK_ForceHighPoly 1.0 version loads all the values correctly, so this makes me think that there could be a solution by maybe using again that part of the code in the first version that lets the game loads all those sliders, or maybe use it in the SliderUnlocker plugin.

So for now, I've been using version 1.0. I'm so glad I had a backup of that version. The only problem is that the game still lags and crashes sometimes when loading H, which then, must be the same reason why it was upgraded.

**Comment by DeathWeasel1337** [comment]
Thank you for the report. In version 1.0 ForceHighPoly simply set the hiPoly flag on characters which caused a lot of unintended side effects such as those crashes. I spoke about this with Marco, he looked through the code for places where the hiPoly flag was used to modify bones for low poly mode and was able to find a fix which will be part of the next version of SliderUnlocker.

https://github.com/IllusionMods/BepisPlugins/issues/69
