### ISSUE TITLE
Follow Neck Setting in Studio Not Consistently Preserved

### ISSUE THREAD

**Issue by Vesperindustrial** [DeathWeasel1337/KK_Plugins#38]
Occasionally characters that have neck/gaze set to "Follow" either dont have the setting saved or it isn't being loaded again after and instead the neck is usually set to anim or fixed (I don't believe its ever been set to Front). Supposedly FKIK plugin but unsure if thats the real cause or not.

Some tested examples:
Removed the fkik plugin, set an issue character to follow on neck direction, saved it. Loading w/o plugin did not cause issue to return nor loading that same scene with plugin.
Then tried with a second issue char in the same scene,  but saving and loading with plugin does not cause an issue either.

Went back to pre-testing SD afterwards, and the issue persists...seems like removing the plugin and resaving the SD makes the issue stop even when the plugin is re-enabled?

**Comment by GeBo1** [comment]
Same issue was also present when replacing characters in a scene.
