### ISSUE TITLE
My female characters can't have balls (Ai Shoujo)

### ISSUE THREAD

**Issue by Elioraa** [DeathWeasel1337/KK_Plugins#40]
Hi, i can't make my futanari character to have balls, it won't appear. pls, i'm a trap loving dude, i need help to satisfy my need. I want to make a trap character, so my futa needs to have balls :(

**Comment by DeathWeasel1337** [comment]
The vanilla female models don't have balls by default, make sure you have AI_UncensorSelector Base.zipmod (or KK_ or EC_ depending on game) in your mods folder. That mod is what adds balls to the female model.

**Comment by Elioraa** [comment]
I have it, but i still can't make the balls appear :(
