### ISSUE TITLE
Please, add the male body model to the girls body selection like in koikatsu. i want to make yaoi! No talking about trap or futa, really talking about boys (Ai Shoujo)

### ISSUE THREAD

**Issue by Kawaii-Youma** [DeathWeasel1337/KK_Plugins#41]
https://1drv.ms/u/s!Ao7RAaVQwcYinhPrmFkn_MRXsC-d?e=UFDkwM 
Why not a male body option?

**Comment by DeathWeasel1337** [comment]
I have no intention of adding male body selection to AI. Since the body is completely different between male and female it's not possible to switch between them like it is in KK.
