### ISSUE TITLE
KK_MaterialEditor non resettable eyeliners textures in character maker

### ISSUE THREAD

**Issue by gievepix** [DeathWeasel1337/KK_Plugins#45]
Weird bug that causes modded eyeliners (and probably any other textures like eyebrows and etc) stick to character forever w/o being able to revert them to original.
There's no * symbol near MainTex label, and pressing "Reset" button does nothing, so i assume that ME treats modded texture(s) as original.
It seems to be related to outfits somehow, because the only way to reproduce this bug i found is:
1) take any character w/o modded eyeliners;
2) import any texture as, for example, cf_m_eyeline_00_up MainTex;
3) change outfit.

After that * symbol near MainTex label disappears and it's not possible to reset texture anymore, until you change outfit back, which makes this symbol appear and "Reset" button work again.
It keeps acting that way even if you save and reload card.

Even more weird thing is that you can import several textures in different outfits. Game will show only the last one, but in order to reset it you have to press "Reset" in every outfit you were importing textures in, reverting texture to one from "previous step" until you get to very 1st.

It's not critical bug, but it can be annoying and **very** confusing at first, not mentioning that it can "bloat" cards (i guess) since it saves all modded textures if you imported several of them in different outfits for some reason.
Found in v2.0.2, tested in v2.0.4

**Comment by DeathWeasel1337** [comment]
Fixed in v2.0.5, thank you for the report
