### ISSUE TITLE
After updating to BepinEx 5.1, the KK_StudioSceneSettings(v1.1) turns malfunction.

### ISSUE THREAD

**Issue by nizhuan-jjr** [DeathWeasel1337/KK_Plugins#47]
[https://cdn.discordapp.com/attachments/555528419442425883/723310771177521232/2020-06-19_065213.png](url)
There shows no options under the bar.

**Comment by nizhuan-jjr** [comment]
[https://cdn.discordapp.com/attachments/555528419442425883/723326043628372018/output_log.txt](url)
This is the output_log

**Comment by DeathWeasel1337** [comment]
I discussed it with Marco and it seems that KKAPI got broken by accident at some point, the next version of KKAPI will have a fix for this
