### ISSUE TITLE
Any plugin for the glitter of the eyes that move along with the eyelids?

### ISSUE THREAD

**Issue by neko47834** [DeathWeasel1337/KK_Plugins#49]
First of all thank you very much for your great work with Koikatsu, sorry there will be a way to make the brightness of the eyes go down or up depending on the eyelids? I have always looked for something like this because when the girls lower their eyelids, the eye brightness stays up and they are no longer seen. thanks and sorry for my english

**Comment by DeathWeasel1337** [comment]
I don't think any such plugin or mod exists, sorry
