### ISSUE TITLE
Is it possible to add more N_name controllers?

### ISSUE THREAD

**Issue by smartluo1833** [DeathWeasel1337/KK_Plugins#66]
I have read https://github.com/DeathWeasel1337/KK_Plugins/wiki/Item-Porting-Guide helps me a lot.

About technical issues

I tried add N_name, N_name2, **N_name3** in .unity3d for a hair acc, 
but in game, at most only 01 and 02 controller is displayed in KK, no 03 controller.

1. What is the reason why 03 cannot be displayed in game?

like pics below, N_name2 bring second controller 02.

2. Is it possible to make the game support N_name3 or more bone controllers?
Like N_name3, N_name4 or even more for long hair?

Advantage:
This will greatly enhance the control ability of hair accessories.
①. Many kinds of curves can be bent with only one hair piece. 
②. Improve the versatility of hair acc.

![2](https://user-images.githubusercontent.com/60388814/101008299-a2f3f780-359c-11eb-996e-ea31d10546a8.jpg)
![3](https://user-images.githubusercontent.com/60388814/101008343-a5eee800-359c-11eb-9ad1-fd46c23b4aee.jpg)

**Comment by DeathWeasel1337** [comment]
Certainly possible, though it would require a plugin to be written. Either a plugin that straight up adds support for more N_move transforms or a plugin that allows you to adjust any accessory bones, similarly to ABMX. Unfortunately, game code only supports two N_move
