### ISSUE TITLE
Add scale into uncensor selector

### ISSUE THREAD

**Issue by Terell2018** [DeathWeasel1337/KK_Plugins#67]
I just would is it possible it you could add scale into uncensor selector so you can resize the penis because some of penis are a-bit long and big and clipping through the body.

**Comment by DeathWeasel1337** [comment]
That's a bit outside the scope of the plugin. You should be able to scale them using ABMX, though
https://github.com/ManlyMarco/ABMX

**Comment by Terell2018** [comment]
Okay.
