### ISSUE TITLE
ClothesUnlocker for HS2

### ISSUE THREAD

**Issue by AaxAisa** [DeathWeasel1337/KK_Plugins#72]
Hello! 
I was wondering if there is a reason why this mod is not available for HS2? 
If there is no such reason, I could maybe try and modify existing project for Koikatsu and build the mod, but I haven't yet delved deep into these games to know if there was an actual incompatibility between the game and this modification, so I decided to ask.

**Comment by DeathWeasel1337** [comment]
Hi, ClothingUnlocker originally removed the gender restriction on clothing in Koikatsu, but the male and female bodies in AI/HS2 are pretty different from each other and would likely not be compatible at all. The feature that unlocks clothing types with each other (i.e. prevents bottoms from being hidden with certain tops) came later and I honestly haven't given much thought to porting that part of the plugin. It's almost certainly possible but I haven't looked in to it so couldn't tell you how difficult it might be. If you'd like to give it a shot you're welcome to do so.

**Comment by AaxAisa** [comment]
I'm actually mostly interested in unlocking more clothing options for male characters. There's SO LITTLE STUFF for the male, it's insane!
So you think female clothes are gonna be incompatible with male ones?

**Comment by DeathWeasel1337** [comment]
I do think they are likely incompatible. You can probably manually convert female clothes to male clothes by modifying the list files, do it for one or two and see how bad the clipping is. List files are in abdata\list\characustom and you can modify them using SB3UGS.

**Comment by AaxAisa** [comment]
I see, thanks! I will try that.
