### ISSUE TITLE
FreeHStudioSceneLoader.KK

### ISSUE THREAD

**Issue by Terell2018** [DeathWeasel1337/KK_Plugins#74]
I just wonder what is FreeHStudioSceneLoader and what is does.

**Comment by DeathWeasel1337** [comment]
It's supposed to be a plugin that allows you to load scenes made in Studio in to Free H, ideally maps. It's not finished and only barely sort-of works. I got bored of working on it.

**Comment by TylitHub** [comment]
One question for you DeathWeasel1337. When are you going to be able to gi back to working on that FreeHStudioSceneLoader because I would like to know how to use it?
