### ISSUE TITLE
null check

### ISSUE THREAD

**Issue by Madevil** [DeathWeasel1337/KK_Plugins#76]
this line needs a null check to prevent some mods with improperly configured MB popping nullref 
https://github.com/DeathWeasel1337/KK_Plugins/blob/master/src/DynamicBoneEditor.Core/DynamicBoneEditor.Controller.cs#L192

changing to this would do
`if (dynamicBone.m_Root?.name == dbData.BoneName)`

**Comment by DeathWeasel1337** [comment]
Fixed in v1.0.3, thanks
